version: "3.4"
networks:
  grpc_example_network:
    external: true
services:
  grpc_helloapp_server_1:
    image: alpine:3.14
    container_name: grpc_helloapp_server_1
    volumes:
      - ./helloapp/bin/hello_server:/bin/hello_server
    command: ./bin/hello_server
    networks:
      - grpc_example_network

  grpc_helloapp_server_2:
    image: alpine:3.14
    container_name: grpc_helloapp_server_2
    volumes:
      - ./helloapp/bin/hello_server:/bin/hello_server
    command: ./bin/hello_server
    networks:
      - grpc_example_network

  helloapp_nginx_lb:
    image: nginx:latest
    container_name: helloapp_nginx_lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - grpc_example_network
